import "./components/header";
import "./pages/home";
import "./pages/login";
import "./pages/signup";
import "./pages/instructions";
import "./pages/lost-pets";
import "./pages/report-lost-pet";
import "./pages/edit-user-report";
import "./pages/report-created";
import "./pages/user-data";
import "./pages/user-reports";
import "./pages/update-data";
import "./pages/update-password";
import "./router";
import { state } from "./state";
import "dotenv/config";
state.init();
